// Generated by CoffeeScript 1.3.1
(function() {

  CMP('jafw.gui.MovingLists', {
    __forms: ['@view'],
    __using: ['jafw.gui.ListView'],
    put: function(DOMContainer, sId, aLists) {
      var i, list, listIndex, _i, _len, _ref, _results,
        _this = this;
      this.id = sId;
      this.container = DOMContainer;
      this.__lists = aLists;
      this.RENDER('@view', this.container, {
        id: this.id,
        lists: this.__lists
      });
      this.listArray = [];
      _ref = this.__lists;
      for (listIndex = _i = 0, _len = _ref.length; _i < _len; listIndex = ++_i) {
        list = _ref[listIndex];
        this.listArray[listIndex] = INSTANCE('jafw.gui.ListView');
        this.listArray[listIndex].put($s('#' + this.id + '_LC_' + listIndex), this.id + '_L_' + listIndex, list.items);
      }
      i = 0;
      _results = [];
      while (i < listIndex) {
        $s('#' + this.id + '_ADD_' + i).onclick = (function(i) {
          return function() {
            if (_this.listArray[i].selected != null) {
              _this.listArray[i + 1].addItem(_this.listArray[i].selected);
              return _this.listArray[i].removeItem(_this.listArray[i].itemIndex($s('.listItemSelected', _this.listArray[i].view)));
            }
          };
        })(i);
        $s('#' + this.id + '_DEL_' + i).onclick = (function(i) {
          return function() {
            if (_this.listArray[i + 1].selected != null) {
              _this.listArray[i].addItem(_this.listArray[i + 1].selected);
              return _this.listArray[i + 1].removeItem(_this.listArray[i + 1].itemIndex($s('.listItemSelected', _this.listArray[i + 1].view)));
            }
          };
        })(i);
        _results.push(++i);
      }
      return _results;
    }
  });

}).call(this);
