// Generated by CoffeeScript 1.3.3
(function() {

  CMP('jafw.gui.TreeView', {
    __forms: ['@item'],
    __css: ['lib/lib/treeView.css'],
    _init: function() {},
    put: function(DOMContainer, oData) {
      DOMContainer.innerHTML = this._handleItem(oData, true);
      return addEventBySelector('hgroup', 'click', function() {
        return toggleClass($s('div.TreeItemBody', this.parentNode), 'hidden');
      });
    },
    _handleItem: function(oItem, isRoot) {
      var body, html, _i, _len, _ref;
      if (!oItem.head) {
        html = this.RENDER('@item', null, {
          body: oItem.body,
          root: isRoot
        });
      } else {
        html = '';
        if (typeof oItem.body === typeof []) {
          _ref = oItem.body;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            body = _ref[_i];
            html += this._handleItem(body, false);
          }
          html = this.RENDER('@item', null, {
            head: oItem.head,
            body: html,
            root: isRoot
          });
        } else {
          html += this.RENDER('@item', null, {
            head: oItem.head,
            body: this._handleItem(body, false),
            root: isRoot
          });
        }
      }
      return html;
    }
  });

}).call(this);
