// Generated by CoffeeScript 1.3.3
(function() {

  CMP('Auth', {
    __forms: ['@LoginPage', '@LoginBar'],
    login: function() {},
    logout: function() {},
    profileEdit: function() {}
  });

}).call(this);
