// Generated by CoffeeScript 1.3.1
(function() {

  JAFW.Session = (function() {

    function Session() {
      var data, storageIndex;
      for (data in sessionStorage) {
        storageIndex = sessionStorage[data];
        if (storageIndex.indexOf('__TPL__') !== -1) {
          sessionStorage.removeItem(storageIndex);
        }
      }
    }

    Session.prototype._storageName = function(sParamName, sNamespace) {
      return 'ns:' + (sNamespace ? sNamespace : 'global') + ':' + sParamName;
    };

    Session.prototype.get = function(sParameter, sNamespace) {
      var res, storageName;
      storageName = this._storageName(sParameter, sNamespace);
      res = sessionStorage[storageName];
      if (res !== null) {
        res = res === "undefined" || res === void 0 ? void 0 : JSON.parse(res);
      }
      return res;
    };

    Session.prototype.set = function(sParameter, oValue, sNamespace) {
      var storageName;
      storageName = this._storageName(sParameter, sNamespace);
      return sessionStorage[storageName] = JSON.stringify(oValue);
    };

    Session.prototype.clear = function() {
      return sessionStorage.clear();
    };

    return Session;

  })();

}).call(this);
