// Generated by CoffeeScript 1.3.1
(function() {
  var __MAIN__;

  window.JAFW = {
    ScriptPath: 'js',
    AppPath: 'js/apps',
    AppCssPath: 'css',
    IncludeLibs: [],
    JafwModules: [
      {
        core: ['app', 'dom', 'signals']
      }, {
        core: ['api', 'launcher']
      }
    ],
    mainFunc: null,
    AppTemplateLoadEngine: function(oRequest, fGoOn) {
      throw 'AppTemplateLoadEngine Not Implemented';
    },
    RenderEngine: {},
    start: function(fMain) {
      var coreScript, head;
      if (fMain != null) {
        JAFW.mainFunc = fMain;
      }
      coreScript = document.createElement('script');
      coreScript.src = "" + JAFW.ScriptPath + "/jafw/core/core.js";
      head = document.querySelector('head');
      return head.appendChild(coreScript);
    }
  };

  window.APP_DELIMITER = '.';

  __MAIN__ = function() {
    return JAFW.RenderEngine = new jSmart();
  };

  JAFW.start(__MAIN__);

}).call(this);
