// Generated by CoffeeScript 1.3.1
(function() {

  CMP('jafw.gui.TableView', {
    __forms: ['@table'],
    __css: ['gui/TableView'],
    _init: function(oConfig) {
      var rowsToRender;
      this.rows = oConfig.rows;
      rowsToRender = this.rows.slice(0, oConfig.maxRows);
      return this.RENDER('@table', oConfig.container, {
        header: oConfig.header,
        rows: rowsToRender,
        width: oConfig.width
      });
    }
  });

}).call(this);
