// Generated by CoffeeScript 1.3.3
(function() {

  CMP('jafw.gui.SideMenu', {
    __forms: ['@menu'],
    __css: ['gui/SideMenu'],
    _init: function(oConfig) {
      var app;
      this.container = oConfig.container;
      this.launcher = new JAFW.Launcher(oConfig.contentContainer.id, false);
      addClass(this.container, 'JAFW_SideMenu');
      this.RENDER('@menu', this.container, {
        menuId: oConfig.id,
        items: oConfig.items
      });
      app = this;
      return addEventBySelector("#" + oConfig.id + " li", 'click', function() {
        addUniqueClass(this, 'Selected', $s("#" + oConfig.id));
        return app.launcher.run(this.dataset['page']);
      });
    }
  });

}).call(this);
