// Generated by CoffeeScript 1.3.3
(function() {
  var handle, wheel;

  handle = function(delta) {
    return container.scrollTop += delta * 15;
  };

  wheel = function(event) {
    var delta;
    delta = 0;
    if (!event) {
      event = window.event;
    }
    if (event.wheelDelta) {
      delta = event.wheelDelta / 120;
    } else if (event.detail) {
      delta = -event.detail / 3;
    }
    if (delta && typeof handle === 'function') {
      handle(delta);
      if (event.preventDefault) {
        event.preventDefault();
      }
      return event.returnValue = false;
    }
  };

  if (window.addEventListener) {
    window.addEventListener('DOMMouseScroll', wheel, false);
  }

  window.onmousewheel = document.onmousewheel = wheel;

}).call(this);
