// Generated by CoffeeScript 1.7.1
(function() {
  var JSONP;

  JSONP = (function() {
    function JSONP() {}

    JSONP.prototype.request = function(url, data) {
      var requestData, script;
      removeNodesBySelector('#JSONPRequester');
      script = $c('script');
      requestData = url + '?' + inSide.Url.encode(data);
      script.src = requestData;
      script.type = 'text/javascript';
      script.id = "JSONPRequester";
      return document.body.appendChild(script);
    };

    return JSONP;

  })();

  inSide.__Register('JSONP', JSONP);

}).call(this);
