// Generated by CoffeeScript 1.7.1
(function() {
  var Upload;

  Upload = (function() {
    function Upload() {
      CONNECT('UPLOAD_FILES', 'upload', this);
    }

    Upload.prototype.upload = function(_arg, emitter) {
      var file, files, formData, param, params, url, value, xhr, _i, _len;
      url = _arg.url, params = _arg.params, files = _arg.files;
      if (!params) {
        params = {};
      }
      formData = new FormData();
      for (param in params) {
        value = params[param];
        formData.append(param, value);
      }
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        formData.append(file.name, file);
      }
      inSide.LoadIndicator.loadMessage = '<div style="margin: auto;margin-top:200px;width:230px;padding:20px;background: #fff;border-radius: 6px"><progress id="UploadIndicator" max="100"></progress><div id="UploadPercent" style="display: inline-block; margin-left: 10px;"></div></div>';
      xhr = new XMLHttpRequest();
      xhr.upload.addEventListener('progress', function(e) {
        var percent;
        if (e.lengthComputable) {
          percent = Math.ceil((e.loaded / e.total) * 100);
          $s('#UploadIndicator').value = percent;
          return $s('#UploadPercent').innerHTML = percent + '%';
        }
      });
      xhr.open('POST', url, true);
      xhr.onload = function(e) {
        EMIT('=UPLOAD_FILES', this.responseText, emitter);
        return inSide.LoadIndicator.hide();
      };
      inSide.LoadIndicator.show();
      xhr.send(formData);
      return null;
    };

    return Upload;

  })();

  inSide.__Register('Uploader', Upload);

}).call(this);
