// Generated by CoffeeScript 1.3.3
(function() {

  CMP('jafw.gui.ToggleButton', {
    __forms: ['@button'],
    __css: ['lib/toggleButton'],
    _init: function() {},
    put: function(DOMContainer) {
      var _this = this;
      this.container = DOMContainer;
      this.state = 0;
      this.RENDER('@button', this.container);
      this.setActive(this.state);
      return $s('div.ToggleButton', this.container).onclick = function() {
        _this.state ^= 1;
        return _this.setActive(_this.state);
      };
    },
    setActive: function(bState) {
      this.state = Number(bState);
      if (bState) {
        addClass($s('div.ToggleButton', this.container), 'Active');
        addClass($s('div.Switch', this.container), 'Active');
        addClass($s('div.SwitchSym', this.container), 'Active');
        $s('div.SwitchSym', this.container).innerHTML = "Вкл";
      } else {
        removeClass($s('div.ToggleButton', this.container), 'Active');
        removeClass($s('div.Switch', this.container), 'Active');
        removeClass($s('div.SwitchSym', this.container), 'Active');
        $s('div.SwitchSym', this.container).innerHTML = "Выкл";
      }
      return typeof this.onStateChange === "function" ? this.onStateChange(bState) : void 0;
    }
  });

}).call(this);
