// Generated by CoffeeScript 1.3.3
(function() {

  if (!(window.JSON != null)) {
    window.JSON = {};
  }

  if (!(window.JSON.parse != null)) {
    window.JSON.prototype.parse = function(sJSONString) {};
  }

  if (!(window.JSON.strigify != null)) {
    window.JSON.prototype.strigify = function(oObject) {};
  }

  if (!(window.Object.defineProperty != null)) {
    window.Object.prototype.defineProperty = function(oObject, sPropName, oDescriptors) {};
  }

  if (!(document.querySelector != null)) {
    document.querySelector = function(sSelector) {};
  }

  if (!(document.querySelectorAll != null)) {
    document.querySelectorAll = function(sSelector) {};
  }

}).call(this);
